### ISSUE TITLE
The link to download the dataset has not yet been made public.

### ISSUE THREAD

**Issue by raysonlaroca** [aa-samad/LP_recognition#6]
The link to download the dataset has not yet been made public.

**Comment by aa-samad** [comment]
Thank you for choosing this dataset for your research.

The dataset was supposed to be uploaded here and made public but due to some privacy issues it's only available with email. If you have emailed, the dataset will be available to you within a week or so.

**Comment by raysonlaroca** [comment]
Ah, ok, good to know!

I am emailing eou right now.
Thank you very much!
